apiVersion: v1
kind: Pod
metadata:
  name: node-api
  namespace: dev
  labels:
    app: node-api
    env: development
spec:
  containers:
    - name: node-api
      image: node:22-alpine
      ports:
        - containerPort: 8080
    - name: logger
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
            echo "Hello from Kubernetes $(date)"
            sleep 5
          done